language: objective-c
osx_image: xcode7.2
xcode_project: Get WiFi Addresses.xcodeproj
xcode_scheme: Get WiFi Addresses
notifications:
  email:
    on_success: change
    on_failure: always
after_success:
    - brew update
    - brew install tree
    - tree
    - echo $BUILT_PRODUCTS_DIR
