language: objective-c
osx_image: xcode7.2
xcode_project: Get WiFi Addresses.xcodeproj
xcode_scheme: Get WiFi Addresses
env:
  global:
  - PROFILE_UUID=testy
notifications:
  email:
    on_success: change
    on_failure: always
after_success:
    - brew update
    - brew install tree
    - tree
